# Use the make_authors.pl to generate the template here!
our %AUTHORS = (
	"Andrew Moore"		=> 'AMOORE',
	"Brandon L Black"	=> 'BLBLACK',
	"Chris Prather"		=> 'PERIGRIN',
	"chromatic"		=> 'CHROMATIC',
	"Cory Watson"		=> 'GPHAT',
	"Dave Rolsky"		=> 'DROLSKY',
	"Dylan William Hardison"=> 'DHARDISON',
	"Flavio Poletti"	=> 'POLETTIX',
	"Florian Ragwitz"	=> 'FLORA',
	"franck cuny"		=> 'FRANCKC',
	"gfx"			=> '',
	"Guillermo Roditi"	=> 'GRODITI',
	"Hans Dieter Pearcey"	=> 'HDP',
	"Jay Hannah"		=> 'JHANNAH',
	"Jay Kuri"		=> 'JAYK',
	"Jesse Luehrs"		=> 'DOY',
	"Jonathan Rockway"	=> 'JROCKWAY',
	"Marc Mims"		=> 'MMIMS',
	"Matt S Trout"		=> 'MSTROUT',
	"nperez"		=> 'NPEREZ',
	"Ricardo Signes"	=> 'RJBS',
	"Ricardo SIGNES"	=> 'RJBS',
	"Rob Kinyon"		=> 'RKINYON',
	"Robert Boone"		=> 'RLB',
	"Scott McWhirter"	=> 'KONOBI',
	"Shawn M Moore"		=> 'SARTAK',
	"Shlomi Fish"		=> 'SHLOMIF',
	"Stash"			=> 'STASH',
	"Stevan Little"		=> 'STEVAN',
	"Todd Hepler"		=> 'THEPLER',
	"Tomas Doran"		=> 'BOBTFISH',
	"Tomas Doran (t0m"	=> 'BOBTFISH',
	"Yuval Kogman"		=> 'NUFFIN',
);

1;
